language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZjtfcJt25AOj54Ga2rszZ9CYQk4tMJe2L8r7+CLJkMt58jYRJy6V/lahogXXpX6CYC5g5B3uMMtvu6u69i7R/y3vddlWyiBEQjSxHIxkpZoH4MK9EQ8DDDlD0uWNVuknr1P2FF76Ndzpp/57qZUScwDIdFLwTkbJfW+zoKNc8NmnEd+fmeiaXJR+xD7mZvfT2uP6Kc9PZPM1rfh9YONwbHMf1OxGiRI3jNakebE1j/spCH2CjJB65omQeUCo7n+g9+kWK8d/V4BXfq7t0tj9MUiJx1Z1pCG1sOJRGwIL6qvDxfIaKmKcNW0JP+THuVUCtsLJbFuCEI/uOW//JjoNlHeqwdGXuHPYki+pLJxfs4kiQ3r23iY9WUveq6u+ROrHBqn9NCTQAEGc7+Kaekda2EvOjvzx0k0tcSGR2XcQn/FI0pumdLqb7R4qzm6yiPjR4QSUYykP97pKBcnHPAF0QO9PvR/8TUijGf66uinfmEIH6NQ4mWxVAnRqWjnnK5kPwuj86r/XHayRHZ7JtpCnmwsbWaAx8/I1en0OxRQErXJPelzcyHMsdggrX4LA2KiwFIEeGJbNSvEH3WSAMkvC7wDisLnRvy4CllwqbRZ1wVNJYjhlvl2qcKozfYDxTx8Lpxql6gPyBqBkW/8yYx7nzq3HjBrGubo06oDN0pIqfzk=
  file:
    - "retext-repeated-words.js"
    - "retext-repeated-words.min.js"
  on:
    tags: true
    node: '9.0'
