language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: sdG1D8AoKINfEQTe/kzZK/VEP7nkGaF+iS6kR0j8mgAQCzN4BytqIKdPS8x0KjZaXZ9K0OfgyMEkflf+sFd1sAjRqsO0DcXOCaAKTrxtRp2g7Y1DTYbEt9+GuFOieQZII2DrovLFRQPpk/LYFQ8zFVU8tIp7KhJol+LXa3uI/3p8Gd9S6Zn7o0dO62KFaXLvQfh0zAHMecvtW2OXAK8halLHABvDF9ytWPPXkdWBJBZYUfJ9oDIRgqQOE5PNrlgI6nsAz/7YHT9XEy6kqrl95mHgSQkgQNDbSje8hlFDMl8zFc2hSUjzIb5I8eQstEOOWR/cSk5BsoKHsjI0vkKSHtS+WkU8U1wsfiH/XsCdxnP89ncI+Ux83/Gz0oMXuOaW7/OOO5tZXTiDRLstKQgIuyfd1jJzGDX5uk+Md22fZGGpSFZxDRFQB83MO7cflBh/h8jGyaAd8XrBq1sZjeoT/WnvGY0bGugbJxfEmeX1aC41aO+3p/lKue5y4L01lmDM3E2i5VOzgt0j7kn5AQi9uF9ersNb4P0ghxNCg7ZqGOounc6dSuYXNJHdy9c7kKedacMCHrLAslzuKHi9E1ZlO9HcAO1vo2W5rUPX5r+YzI10K3PO1tM5YfOP0ZmW1cBmUjsPzZyxm662E628k5aAimqfeXEo9m5x6oPl5tnDc2k=
  file:
    - 'retext-repeated-words.js'
    - 'retext-repeated-words.min.js'
  on:
    tags: true
